services:

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wp_db:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - db
  db:
    build: ./requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    expose: # permet d'exposer un port sans le publier sur l'hote. Present dans le docker compose mais pas dans l'hote
      - 3306
    environment: # environnement mySQL pour plus de flexibilite avec Wordpress 
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
  nginx:
    build: ./requirements/nginx
    # env_file: ./env.env
    ports: 
      - "8080:80"
      - "443:443"
    volumes:
      # - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - wp_db:/var/www/html
    depends_on:
      - wordpress
    # volumes:
      # - ./nginx:/etc/nginx/conf.d
      # - ./nginx/certs:/etc/nginx/certs
    # volumes:
    #   - ./debug.conf:/etc/nginx/nginx.conf

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bpoyet/data/mariadb

  wp_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bpoyet/data/wordpress