services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    env_file: .env
    ports: 
      - "443:443"
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ../secrets:/etc/nginx/certs:ro
    networks:
      - wp-networks

  wordpress:
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
        # condition: service_healthy
    expose:
      - "9000"
    networks:
      - wp-networks

  mariadb:
    build: ./requirements/mariadb
    env_file: .env
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    expose: 
      - 3306
    ports:
      - "3306:3306"
    networks:
      - wp-networks

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bpoyet/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bpoyet/data/wordpress

networks:
  wp-networks:
    driver: bridge