services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    env_file: .env
    ports: 
      - "443:443"
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      # - mariadb:/var/lib/mysql
      # - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../secrets:/etc/nginx/certs:ro
      # - db_data:/var/lib/mysql
    networks:
      - wp-networks

  wordpress:
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - mariadb
    expose:
      - "9000"
    networks:
      - wp-networks

  mariadb:
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    expose: 
      - 3306
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wp-networks

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bastpoy/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bastpoy/data/wordpress

networks:
  wp-networks:
    driver: bridge