services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    env_file: .env
    ports: 
      - "443:443"
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ../secrets:/etc/nginx/certs:ro
    networks:
      - wp-networks

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
      - redis
    expose:
      - "9000"
    networks:
      - wp-networks

  mariadb:
    build: ./requirements/mariadb
    env_file: .env
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    expose: 
      - 3306
    ports:
      - "3306:3306"
    networks:
      - wp-networks
  
  redis:
    build: ./requirements/bonus/redis
    image: redis
    ports:
      - '6379:6379'
    restart: always
    expose:
      - '6379'
    networks:
      - wp-networks

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    restart: always
    networks:
      - wp-networks
    volumes:
      - wordpress:/home/vsftpd:ro
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      - FTP_USER=ftp
      - FTP_PASS=ftp
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bastpoy/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bastpoy/data/wordpress

networks:
  wp-networks:
    driver: bridge