services:
  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    depends_on:
      - mariadb
    restart: always
    # ports:
    #   - "8000:80"
  mariadb:
    build: ./requirements/mariadb
    volumes:
      # - db_data:/var/lib/mysql
      - mariadb:/var/lib/mysql
    restart: always
    # command: '--default-authentication-plugin=mysql_native_password'
    # expose: # permet d'exposer un port sans le publier sur l'hote. Present dans le docker compose mais pas dans l'hote
    #   - 3306
    ports:
      - "3306:3306"
    environment: # environnement mySQL pour plus de flexibilite avec Wordpress 
      # - MYSQL_ROOT_PASSWORD=somewordpress
      # - MYSQL_DATABASE=wordpress
      # - MYSQL_USER=wordpress
      # - MYSQL_PASSWORD=wordpress
      MARIADB_ROOT_PASSWORD: example 
  nginx:
    build: ./requirements/nginx
    env_file: ./env.env
    ports: 
      - "443:80"
    depends_on:
      - wordpress
      - mariadb
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - wordpress:/var/www/html
      - mariadb:/var/lib/mysql
      # - word:/var/www/html
      # - db_data:/var/lib/mysql
      # - ./nginx:/etc/nginx/conf.d
      # - ./nginx/certs:/etc/nginx/certs
      # - ./debug.conf:/etc/nginx/nginx.conf

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bpoyet/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bpoyet/data/wordpress